### ISSUE TITLE
Error response from wallet: error: couldn't connect to server

### ISSUE THREAD

**Issue by vanderval** [BuckCoin/buck-gui-wallet-win#4]
Good afternoon

Can someone help me with the error below? Thank you.

Environment PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp;C:\app\user\product\11.2.0\client_2\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
[main] [Tue May 08 15:58:47 BRT 2018] [INFO] Using Buck utilities: zcashd: C:\Windows\System32\zcashd.exe, zcash-cli: C:\Windows\System32\zcash-cli.exe
[main] [Tue May 08 15:58:49 BRT 2018] [INFO] Using Buck utilities: zcashd: C:\Windows\System32\zcashd.exe, zcash-cli: C:\Windows\System32\zcash-cli.exe
[main] [Tue May 08 15:58:51 BRT 2018] [ERROR] Unexpected error:
com.vaklinov.zcashui.ZCashClientCaller$WalletCallException: Error response from wallet: error: couldn't connect to server: EOF reached (code 1)
(make sure server is running and you are connecting to the correct RPC port)

        at com.vaklinov.zcashui.ZCashClientCaller.executeCommandAndGetSingleStringResponse(ZCashClientCaller.java:1117)
        at com.vaklinov.zcashui.ZCashClientCaller.executeCommandAndGetSingleStringResponse(ZCashClientCaller.java:1088)
        at com.vaklinov.zcashui.ZCashClientCaller.executeCommandAndGetJsonValue(ZCashClientCaller.java:1056)
        at com.vaklinov.zcashui.ZCashClientCaller.executeCommandAndGetJsonArray(ZCashClientCaller.java:1034)
        at com.vaklinov.zcashui.ZCashClientCaller.getWalletPublicTransactions(ZCashClientCaller.java:236)
        at com.vaklinov.zcashui.DashboardPanel.getTransactionsDataFromWallet(DashboardPanel.java:609)
        at com.vaklinov.zcashui.DashboardPanel.<init>(DashboardPanel.java:148)
        at com.vaklinov.zcashui.ZCashUI.<init>(ZCashUI.java:141)
        at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:596)

**Comment by BuckCoin** [comment]
(1) If you are running other crypto wallets, close them before running BUCK.

(2) Update your video drivers to the latest available versions

(3) Update your ethernet to the latest available versions

(4) Update your wifi drivers to the latest available versions

(5) Update to the latest version of JAVA: https://java.com/en/download/

Reboot, then try again.

**Comment by vanderval** [comment]
Perfect. tks.
